### ISSUE TITLE
yarn v3 breaks install

### ISSUE THREAD

**Issue by georgyo** [stephank/yarn-plugin-nixify#2]
The current install steps say `yarn set version berry` however that installs yarn 3.0 now.  And yarn 3.0 removed `bstatePath`

Worse, there doesn't seem to be an ability to install a recent yarn 2.x 

```
% yarn --version
3.0.0
```
```
% yarn
➤ YN0000: ┌ Resolution step
➤ YN0013: │ Slackdown@https://github.com/Half-Shot/slackdown.git#commit=efd8934a3d9c3bf0064c0b217c5cf6b62ee697e4 can't be found in the cache and will be fetched from GitHub
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0000: └ Completed in 3s 171ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.3.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 21s 383ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 424ms
➤ YN0001: Error: Invalid configuration key "bstatePath"
    at co.get (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:294:27366)
    at /home/shammas/tmp/matrix-appservice-slack/.yarn/plugins/yarn-plugin-nixify.cjs:1:9979
    at async afterAllInstalled (/home/shammas/tmp/matrix-appservice-slack/.yarn/plugins/yarn-plugin-nixify.cjs:1:8392)
    at async co.triggerHook (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:295:2989)
    at async Fe.install (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:306:4639)
    at async /home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:348:14731
    at async Function.start (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:275:2287)
    at async Dp.execute (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:348:14631)
    at async Dp.validateAndExecute (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:197:620)
    at async ts.run (/home/shammas/tmp/matrix-appservice-slack/.yarn/releases/yarn-berry.cjs:211:1846)
➤ YN0000: Failed with errors in 25s 50ms
```

The fix seems to be 
```
% yarn set version '~2'
```

**Comment by stephank** [comment]
I got around to making the Yarn 3 changes, and it's on a separate branch. You can try this out with:

```
yarn plugin import https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/feat/yarn3/dist/yarn-plugin-nixify.js
```

Would like to know if it works for you! 🙂
